# Generated by Django 5.0.2 on 2024-02-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('fan_name', models.CharField(max_length=200)),
                ('competitor_name', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('twitter_handle', models.CharField(max_length=30)),
                ('telegram_handle', models.CharField(max_length=30)),
                ('music_url', models.URLField(default='')),
                ('is_group', models.BooleanField(default=False)),
                ('performer_two', models.CharField(max_length=200)),
                ('performer_three', models.CharField(max_length=300)),
                ('performer_four', models.CharField(max_length=300)),
                ('performer_five', models.CharField(max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
