# Generated by Django 5.0.11 on 2025-01-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dancecomp', '0002_competitor_panel_state_competitor_state_changed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='panel_state',
            new_name='competitor_state',
        ),
    ]
