# Generated by Django 5.0.11 on 2025-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancecomp', '0003_rename_panel_state_competitor_competitor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='performer_five',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='performer_four',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='performer_three',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='performer_two',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
