# Generated by Django 5.0.2 on 2024-02-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysAvailable',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('available_scheduling', models.BooleanField(default=False)),
                ('available_party', models.BooleanField(default=False)),
                ('party_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('max_merchants', models.IntegerField(default=0)),
                ('max_party_rooms', models.IntegerField(default=0)),
                ('submissions_end', models.DateField()),
                ('module_panels_enabled', models.BooleanField(default=False)),
                ('module_merchants_enabled', models.BooleanField(default=False)),
                ('module_performers_enabled', models.BooleanField(default=False)),
                ('module_partyfloor_enabled', models.BooleanField(default=False)),
                ('module_competitors_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
