# Generated by Django 5.0.9 on 2024-11-16 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('ROOM_PANELS', 'Panel Space')], default='ROOM_PANELS', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panels_start', models.DateTimeField()),
                ('panels_end', models.DateTimeField()),
                ('performers_start', models.DateTimeField()),
                ('performers_end', models.DateTimeField()),
                ('day_available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daysavailable')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
