# Generated by Django 5.0.11 on 2025-01-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventroom_schedulingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
