# Generated by Django 5.0.11 on 2025-10-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voucher_performers',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='voucher_volunteer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
