# Generated by Django 5.2.13 on 2026-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_voucher_performers_event_voucher_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysavailable',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventroom',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulingconfig',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='daysavailable',
            name='key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
