# Generated by Django 5.0.2 on 2024-02-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('fan_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=200)),
                ('wares_description', models.TextField(verbose_name='Description of Wares')),
                ('helper_legal_name', models.CharField(blank=True, max_length=200)),
                ('helper_fan_name', models.CharField(blank=True, max_length=200)),
                ('special_requests', models.TextField(blank=True)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('merchant_state', models.CharField(choices=[('STATE_NEW', 'New'), ('STATE_ACCEPTED', 'Accepted'), ('STATE_PAYMENT', 'Payment Requested'), ('STATE_CONFIRMED', 'Payment Confirmed'), ('STATE_ASSIGNED', 'Table Assigned'), ('STATE_WAITLISTED', 'Waitlisted'), ('STATE_DENIED', 'Denied'), ('STATE_DELETED', 'Deleted'), ('STATE_OLD', 'Migrated Data')], default='STATE_NEW', max_length=20)),
                ('state_changed', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('table_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchants.table')),
            ],
        ),
    ]
