# Generated by Django 5.2.8 on 2026-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='underpaw_interest',
            field=models.BooleanField(default=False),
        ),
    ]
