# Generated by Django 5.2.11 on 2026-04-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_underpaw_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='underpaw_interest',
            field=models.BooleanField(default=False, help_text='underPAW is PAWCon\'s Night Market. You Can find information <a href="https://pacanthro.org/underpaw">here</a>', verbose_name='Interested in underPAW'),
        ),
    ]
