# Generated by Django 5.2.11 on 2026-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_merchant_underpaw_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_body', models.TextField()),
                ('card_cta', models.CharField(help_text='Button Text', max_length=50, verbose_name='Card Call To Action')),
                ('page_interstitial', models.TextField()),
                ('page_apply', models.TextField(verbose_name='Application')),
                ('page_confirmation', models.TextField()),
                ('email_submit', models.TextField()),
                ('email_accepted', models.TextField()),
                ('email_payment_requested', models.TextField()),
                ('email_payment_confirmed', models.TextField()),
                ('email_declined', models.TextField()),
                ('email_waitlisted', models.TextField()),
                ('email_assigned', models.TextField()),
            ],
        ),
    ]
