# Generated by Django 5.2.11 on 2026-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchantcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcontent',
            name='email_payment_remind',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
