# Generated by Django 5.2.13 on 2026-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_merchantcontent_email_payment_remind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
