# Generated by Django 5.0.2 on 2024-02-08 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesAvailable',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('fan_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('twitter_handle', models.CharField(max_length=30)),
                ('telegram_handle', models.CharField(max_length=30)),
                ('volunteer_history', models.TextField()),
                ('special_skills', models.TextField()),
                ('avail_setup', models.BooleanField(verbose_name='Available Setup')),
                ('avail_teardown', models.BooleanField(verbose_name='Available Teardown')),
                ('volunteer_state', models.CharField(choices=[('STATE_NEW', 'New'), ('STATE_ACCEPTED', 'Accepted'), ('STATE_ASSIGNED', 'Assigned'), ('STATE_WAITLIST', 'Waitlisted'), ('STATE_DENIED', 'Denied'), ('STATE_DELETED', 'Deleted'), ('STATE_OLD', 'Migrated Data')], default='STATE_NEW', max_length=20)),
                ('state_changed', models.DateField(auto_now_add=True)),
                ('days_available', models.ManyToManyField(to='core.daysavailable')),
                ('department_interest', models.ManyToManyField(to='core.department')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('time_availble', models.ManyToManyField(to='volunteers.timesavailable')),
            ],
        ),
    ]
