# Generated by Django 5.0.11 on 2025-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_volunteertask_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='twitter_handle',
            field=models.CharField(max_length=30, verbose_name='Twitter/BSky Handle'),
        ),
    ]
