# Generated by Django 5.2.11 on 2026-04-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_alter_volunteer_twitter_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_body', models.TextField()),
                ('card_cta', models.CharField(help_text='Button Text', max_length=50, verbose_name='Card Call To Action')),
                ('page_interstitial', models.TextField()),
                ('page_apply', models.TextField(verbose_name='Application')),
                ('page_confirmation', models.TextField()),
                ('email_submit', models.TextField()),
                ('email_accepted', models.TextField()),
                ('email_declined', models.TextField()),
            ],
        ),
    ]
