# Generated by Django 5.2.11 on 2026-04-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_volunteercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
