# Generated by Django 5.2.13 on 2026-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_volunteer_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesavailable',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timesavailable',
            name='key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
