# Generated by Django 5.2.13 on 2026-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_timesavailable_deleted_alter_timesavailable_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=30, verbose_name='Twitter/BSky Handle'),
        ),
    ]
