# Generated by Django 5.0.2 on 2024-02-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('fan_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('twitter_handle', models.CharField(max_length=30)),
                ('telegram_handle', models.CharField(max_length=30)),
                ('hotel_primary', models.CharField(max_length=200, verbose_name='Primary Name On Hotel Reservation')),
                ('hotel_ack_num', models.CharField(max_length=50, unique=True, verbose_name='Hotel Reservation Number')),
                ('ack_no_smoking', models.BooleanField(default=False, verbose_name='No Smoking of any kind -inside- the room or on the balcony (this includes vapes)')),
                ('ack_amplified_sound', models.BooleanField(default=False, verbose_name='Amplified sound is not allowed on the balcony (inside rooms at reasonable levels is accepted)')),
                ('ack_verify_age', models.BooleanField(default=False, verbose_name="You must check ID's before handing out wristbands.")),
                ('ack_wristbands', models.BooleanField(default=False, verbose_name='Only guests with wristbands indicating drinking age may have alcohol')),
                ('ack_closure_time', models.BooleanField(default=False, verbose_name='The party floor closes to the public at 2AM, and normal hotel rules come into effect.')),
                ('ack_suspension_policy', models.BooleanField(default=False, verbose_name='Failure to bide by Con Staff/Hotel Security requests will result in party suspension (zero tolerance)')),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('host_state', models.CharField(choices=[('STATE_NEW', 'New'), ('STATE_ACCEPTED', 'Accepted'), ('STATE_ASSIGNED', 'Assigned'), ('STATE_WAITLIST', 'Waitlisted'), ('STATE_DENIED', 'Denied'), ('STATE_DELETED', 'Deleted'), ('STATE_OLD', 'Migrated Data')], default='STATE_NEW', max_length=20)),
                ('state_changed', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('party_days', models.ManyToManyField(to='core.daysavailable')),
            ],
        ),
    ]
