# Generated by Django 5.0.11 on 2025-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyfloor', '0002_alter_partyhost_host_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyhost',
            name='party_description',
            field=models.TextField(help_text='A description of your party for our website.', null=True),
        ),
        migrations.AddField(
            model_name='partyhost',
            name='party_name',
            field=models.CharField(help_text='The name of your party for our website.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partyhost',
            name='rbs_certification',
            field=models.CharField(max_length=50, null=True, verbose_name='RBS Certification'),
        ),
        migrations.AlterField(
            model_name='partyhost',
            name='ack_amplified_sound',
            field=models.BooleanField(default=False, verbose_name='Amplified sound is not allowed on the balcony (inside rooms at reasonable levels is acceptable).'),
        ),
        migrations.AlterField(
            model_name='partyhost',
            name='ack_suspension_policy',
            field=models.BooleanField(default=False, verbose_name='Failure to bide by Con Staff/Hotel Security requests will result in party suspension (zero tolerance).'),
        ),
        migrations.AlterField(
            model_name='partyhost',
            name='telegram_handle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partyhost',
            name='twitter_handle',
            field=models.CharField(max_length=30, null=True, verbose_name='Telegram or BSky Handle'),
        ),
    ]
