# Generated by Django 5.0.2 on 2024-02-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('fan_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('twitter_handle', models.CharField(max_length=30)),
                ('telegram_handle', models.CharField(max_length=30)),
                ('biography', models.TextField()),
                ('dj_history', models.TextField()),
                ('set_link', models.URLField(help_text='Please provide a link to a set of music from your SoundCloud or other similar service (DropBox, Box, YouTube, etc). It should be at least 30 mins in length and showcase your unique style.')),
                ('performer_state', models.CharField(choices=[('STATE_NEW', 'New'), ('STATE_ACCEPTED', 'Accepted'), ('STATE_ASSIGNED', 'Assigned'), ('STATE_WAITLIST', 'Waitlisted'), ('STATE_DENIED', 'Denied'), ('STATE_DELETED', 'Deleted'), ('STATE_OLD', 'Migrated Data')], default='STATE_NEW', max_length=20)),
                ('state_changed', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
