# Generated by Django 5.2.11 on 2026-04-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_alter_performer_twitter_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_body', models.TextField()),
                ('card_cta', models.CharField(max_length=50)),
                ('page_interstitial', models.TextField()),
                ('page_apply', models.TextField()),
                ('page_confirmation', models.TextField()),
                ('email_confirm', models.TextField()),
                ('email_accepted', models.TextField()),
                ('email_declined', models.TextField()),
                ('email_waitlisted', models.TextField()),
            ],
        ),
    ]
