# Generated by Django 5.2.11 on 2026-04-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0004_performercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='performercontent',
            name='email_assigned',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performercontent',
            name='card_cta',
            field=models.CharField(help_text='Button Text', max_length=50, verbose_name='Card Call To Action'),
        ),
        migrations.AlterField(
            model_name='performercontent',
            name='page_apply',
            field=models.TextField(verbose_name='Application'),
        ),
    ]
