# Generated by Django 5.2.11 on 2026-04-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0005_performercontent_email_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performercontent',
            old_name='email_confirm',
            new_name='email_submit',
        ),
    ]
