# Generated by Django 5.0.2 on 2024-02-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelDuration',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PanelSlot',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('fan_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('twitter_handle', models.CharField(max_length=30)),
                ('telegram_handle', models.CharField(max_length=30)),
                ('panelist_bio', models.TextField(verbose_name='Panelist Bio')),
                ('panel_name', models.CharField(max_length=100)),
                ('panel_description', models.TextField()),
                ('equipment_needs', models.TextField()),
                ('mature_content', models.BooleanField(verbose_name='Does your panel contain mature content?')),
                ('check_ids', models.BooleanField(verbose_name="I Agree to check ID's")),
                ('panel_state', models.CharField(choices=[('STATE_NEW', 'New'), ('STATE_ACCEPTED', 'Accepted'), ('STATE_ASSIGNED', 'Assigned'), ('STATE_WAITLIST', 'Waitlisted'), ('STATE_DENIED', 'Denied'), ('STATE_DELETED', 'Deleted'), ('STATE_OLD', 'Migrated Data')], default='STATE_NEW', max_length=20)),
                ('state_changed', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('panel_day', models.ManyToManyField(to='core.daysavailable')),
                ('panel_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.panelduration')),
                ('panel_times', models.ManyToManyField(to='panels.panelslot')),
            ],
        ),
    ]
