# Generated by Django 5.0.9 on 2024-11-16 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventroom_schedulingconfig'),
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='scheduled_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_day', to='core.daysavailable'),
        ),
        migrations.AddField(
            model_name='panel',
            name='scheduled_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventroom'),
        ),
        migrations.AddField(
            model_name='panel',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_state',
            field=models.CharField(choices=[('STATE_NEW', 'New'), ('STATE_ACCEPTED', 'Accepted'), ('STATE_ASSIGNED', 'Assigned'), ('STATE_CANCELED', 'Canceled'), ('STATE_WAITLIST', 'Waitlisted'), ('STATE_DENIED', 'Denied'), ('STATE_DELETED', 'Deleted'), ('STATE_OLD', 'Migrated Data')], default='STATE_NEW', max_length=20),
        ),
    ]
