# Generated by Django 5.0.11 on 2025-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_alter_panel_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='twitter_handle',
            field=models.CharField(max_length=30, verbose_name='Twitter/BSky Handle'),
        ),
    ]
