name: Django CI

on:
  pull_request:
    branches: [ "main", "master" ] # Triggers on pull requests to the 'main' branch
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main", "master" ] # Also runs on direct pushes to 'main'

jobs:
  django_tests:
    runs-on: ubuntu-latest # Specifies the operating system to run the job on

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13" # Specify your desired Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_postgres.txt # Installs project dependencies from requirements.txt
    - name: Run Tests
      env:
        # Set the Django settings module environment variable
        DJANGO_SETTINGS_MODULE: paw.test_settings
        DJANGO_SECRET_KEY: "some_really_secret_key_for_unit_tests"
        DEBUG: "True"
        EMAIL_BACKEND: "django.core.mail.backends.filebased.EmailBackend"
        CONCAT_CLIENT_ID: "3"
        CONCAT_CLIENT_SECRET: "stuff"
        CONCAT_CLIENT_NAME: "concat-test"
      run: |
        python manage.py test --verbosity 3 # Executes Django's built-in test command
